### ISSUE TITLE
Toggled Filters not saving when closing and reloading Blish

### ISSUE THREAD

**Issue by davidlukerice** [blish-hud/Pathing#70]
I tend to have most of my marker packs turned off until I need them for something, so I'll go through and toggle them off.
When I close Blish or GuildWars and then load Blish or the game back up, all the markers are back to being turned on.

Launching GW and BlishHud through Gw2 LaunchBuddy v2.4.2
BlishHud: v0.11.4
Pathing: v0.17.3

**Comment by dlamkins** [comment]
Hey @davidlukerice, this is almost always due to an anti-virus blocking us from saving.

If you can provide us a copy of your logs, we can confirm by looking for `UnauthorizedAccessException` in the logs.  Logs can be found at `Documents\Guild Wars 2\addons\blishhud\logs`.

If this is the case, you'll need to manually add Blish HUD to the explicitly allowed list in your anti-virus software.

**Comment by davidlukerice** [comment]
Yup, that was exactly it! Thanks!
Had the error
```
13:29:52.7195 | ERROR | BhModule.Community.Pathing.State.CategoryStates | Failed to write categories.txt (C:\...\Documents\Guild Wars 2\addons\blishhud\markers\data\states\categories.txt).
```
And just needed to add the exception in Avast Antivirus.

**Comment by dlamkins** [comment]
Thanks for confirming!  Have a good one and don't hesitate to reach out if you have any further questions or issues.  🙂
